# Generated by Django 4.2.30 on 2026-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='stockrecord_symbol_date_uniq'),
        ),
    ]
