# Generated by Django 4.2.30 on 2026-09-11 06:30

from django.db import migrations, models
from django.db.models import F


def _backfill_ohlc_from_close(apps, schema_editor):
    """既存レコード（close のみ手入力・open/high/low 不明）に close 値を埋める。

    ローソク足チャートで平坦なローソク（実体なし）として表示できるようにする。
    """
    StockRecord = apps.get_model('app', 'StockRecord')
    StockRecord.objects.filter(open__isnull=True).update(
        open=F('close'), high=F('close'), low=F('close'),
    )


def _revert_backfill(apps, schema_editor):
    """backfill を取り消す（open/high/low を None に戻す）。"""
    StockRecord = apps.get_model('app', 'StockRecord')
    StockRecord.objects.filter(volume__isnull=True).update(
        open=None, high=None, low=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        # 既存レコードの open/high/low を close で埋める
        migrations.RunPython(_backfill_ohlc_from_close, _revert_backfill),
    ]
